### ISSUE TITLE
This is the config file

### ISSUE THREAD

**Issue by harrinp** [harrinp/PAT#1]
#ifndef CONFIG_HPP
#define CONFIG_HPP

#include <unistd.h>

// MYSQL parameters
static const std::string URL = "tcp://127.0.0.1:3306";
static const std::string USER = "root";
static const std::string PASSWORD = "";

// OANDA parameters
static const std::string ACCOUNT_ID = "<Put id here>";
static const std::string ACCESS_TOKEN = "<Put token here>";

#endif

**Comment by harrinp** [comment]
put that in Config.hpp

**Comment by Gyrfalcon5** [comment]
I added this to the readme so hopefully we don't need this here anymore. I'm going to close it, let me know if you feel it needs to be reopened.
