### ISSUE TITLE
Compiling on the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by sdvaughan** [harrinp/PAT#3]
General
--------------------------

Make sure you download the full Poco install, then navigate to your Downloads folder with:

`cd "/mnt/c/Users/%YOURUSERNAME%/Downloads/"`

Then copy the Poco tar.gz file to your home directory:

`cp poco-X.X.X-all.tar.gz ~`

After copying the file, follow the instructions in the README to unzip and unpack the file.

After configuring and making Poco, run the following commands (from the folder in which you built Poco):

`sudo cp -r Foundation/include/Poco/. /usr/include/Poco/`
`sudo cp -r Util/include/Poco/. /usr/include/Poco/`
`sudo cp -r JSON/include/Poco/. /usr/include/Poco/`

`sudo cp -r lib/Linux/x86_64/. /usr/local/lib`

For Windows Subsystem for Linux
-----------------------

In any text editor, open:

`~/.bashrc`

At the bottom of the file, add the line:

`LD_LIBRARY_PATH=/usr/local/lib`

Restart the terminal, then run the following command:

`sudo ldconfig`

Then compile the code in your project folder with the "make" commands.

Follow the README from the point after compiling.

**Comment by Gyrfalcon5** [comment]
All of this information should now be in the readme. Let me know if there is anything else you think needs to go in there on this subject by reopening this issue.
